### ISSUE TITLE
Threads Feature

### ISSUE THREAD

**Issue by psi-4ward** [utterance/utterances#230] opened 2019-12-05 12:49 UTC
Hi,
I wonder if you thought about a thread feature where ppl can answer to a specific topic.
So the idea is that a _thread_ is an Issue (with custom topic) and assign to a page using labels.
In addition we could mark a thread als "solved" by closing the issue.

**Comment by jdanyow** [comment] 2019-12-30 19:39
@psi-4ward check out what we did on docs.microsoft.com with respect to threads:
https://docs.microsoft.com/en-us/azure/cosmos-db/index-policy#feedback

Is that what you're looking for?

**Comment by psi-4ward** [comment] 2019-12-30 20:08
> @psi-4ward check out what we did on docs.microsoft.com with respect to threads:
> https://docs.microsoft.com/en-us/azure/cosmos-db/index-policy#feedback
> 
> Is that what you're looking for?

YES! That is awesome! Can you give me a hint how you implemented it?

**Comment by jdanyow** [comment] 2020-01-19 19:48
Nice! Closing as duplicate of #39. The code for threads is similar, the primary differences are:

- We're using the github issue search to find multiple issues that have an identifier in the issue body. In the docs.microsoft.com case it's a guid but for utterances this would probably need to be hashed from the post pathname, title, or description.
- The UI uses a tabbed issue list.
- The UI has two types of forms: comment and issue. The issue form permits entering a title in addition to the description.

**Closed** 2020-01-19 19:48 UTC
Labels: enhancement
