### ISSUE TITLE
it support put the comment input box in the top/ get the count of the comments?

### ISSUE THREAD

**Issue by jerryc127** [utterance/utterances#262] opened 2020-02-07 16:01 UTC
it support put the comment input box in the top?
and provided a function to call to get the count of the comments?

**Comment by jdanyow** [comment] 2020-02-16 00:03
duplicate of #182

**Closed by jdanyow** 2020-02-16 00:03 UTC
Labels: duplicate

**Comment by jerryc127** [comment] 2020-02-16 08:45
thx,
it seem not merge the pull requests,
and the second question:
can provided a function to call to get the count of the comments?
