### ISSUE TITLE
500 error when signing in

### ISSUE THREAD

**Issue by herb123456** [utterance/utterances#163] opened 2019-05-19 07:17 UTC
There are no problem when I logged in github before I click "sign in to comment" button.

But I got 500 error when I use Incognito window or logged out from github.

The full url is:

```
https://github.com/login/oauth/authorize?client_id=Iv1.a44a2bace9e1c9a9&redirect_uri=https%3A%2F%2Fapi.utteranc.es%2Fauthorized&state=f4d10c352e735e652aa1a34f9ImLNaffI4xEBCvGnZUJh9tXm%2FBFvPlEF6A%2FGEFP3l4Ap%2B34pGI0dIjlwH9h8pRj6ccss%2FigcWF%2B7HW6YJMtc3m8xR1vtTKSxDbnDAbJW9opWfVjUH83%2BnO%2BPCKowtdotB2dD2LLm96r0C1kxtAhsfzaNIzZ7rOxR%2BgODxh6GjtzXGxfe%2FWnYQqsGkkxLuw%2FViDVGoPqqJFEEh4%3D
```

**Comment by jdanyow** [comment] 2019-05-23 02:08
@herb123456 I can't reproduce this. Are you still able to repro this? Any additional details you can share?

**Comment by jdanyow** [comment] 2019-05-31 00:55
closing- will reopen if ore info is received

**Closed by jdanyow** 2019-05-31 00:55 UTC

**Comment by herb123456** [comment] 2019-06-07 02:08
@jdanyow sorry for the late reply.

I think it was github temporary error, and now it's everything ok.

nice project!
