### ISSUE TITLE
sometime it's scollable after issue is loaded

### ISSUE THREAD

**Issue by Trim21** [utterance/utterances#234] opened 2019-12-19 20:17 UTC
![correct](https://user-images.githubusercontent.com/13553903/71206477-95882380-22df-11ea-9b16-1b3278e5b304.gif)

https://blog.wolfogre.com/posts/golang-package-rejection/

it also happed on https://utteranc.es/

can be reproduced both on firefox 71.0 64-bit and CentBrowser(Chromium 78.0.3904.97)
I have some custom stylus and browser minim font size(18px) and zoom(120%)  but they are irrelative. 

**I found it happed comments are rendered when comments element is not visible.**

maybe we should get some extra height for `.utterances`, about 20px.

if you are using vimium(click inner element and press `d` or `u`), you can find it happened everytime. The inner element is always higher than the outside element, but not every time it's scrollable.

my workaround
```js
window.addEventListener("message", function (event) {
    // For Chrome, the origin property is in the event.originalEvent.
    let origin = event.origin || event.originalEvent.origin;
    if (origin !== "https://utteranc.es") {
      return
    }
    if (event.data && event.data.type === 'resize' && event.data.height) {
      setTimeout(function () {
        $('div.utterances')[0].style.height = `${event.data.height + 15}px`
      }, 500)
    }
  }
  , false);
```

**Comment by Trim21** [comment] 2019-12-19 21:06
find real reason: [Chromium Wheel Smooth Scroller](https://chrome.google.com/webstore/detail/chromium-wheel-smooth-scr/khpcanbeojalbkpgpmjpdkjnkfcgfkhb)

I disable this extension and it works as expected...

But I do hold `.utterances` could have 30px extra height as the inner element is indeed higher than the outside element.

**Comment by Trim21** [comment] 2019-12-19 21:45
find old commit, it's 15px then...

**Comment by jdanyow** [comment] 2019-12-30 19:41
closing as this was caused by user's chrome extension.

**Closed by jdanyow** 2019-12-30 19:41 UTC
