### ISSUE TITLE
2 Pages have same comments

### ISSUE THREAD

**Issue by RohanNagar** [utterance/utterances#119] opened 2019-02-07 23:37 UTC
First of all thanks so much for utterances.

I'm noticing that two of my posts have the same comments on them. I'm using the `title` issue term, and the titles of the pages are different, so I'm not sure why it's picking up the same one.

This is the latest page I just published:
https://rohannagar.github.io/2019-02-07/migrating-aws-sdk-version

This is the other page with the same comments.
https://rohannagar.github.io/2017-10-01/simple-facebook-oauth-using-sfauthenticationsession

This page was published a while ago and corresponds to this issue:
https://github.com/RohanNagar/rohannagar.github.io/issues/2

Thanks!

**Comment by jdanyow** [comment] 2019-02-08 03:02
This is strange. I can reproduce this on github.com/issues as well:
1. https://github.com/issues?utf8=%E2%9C%93&q=%22Facebook+OAuth+using+SFAuthenticationSession+on+iOS+11+%C2%B7+Rohan+Nagar%22+is%3Aissue+in%3Atitle+repo%3A%22RohanNagar%2Frohannagar.github.io%22
2. https://github.com/issues?utf8=%E2%9C%93&q=%22Migrating+to+Version+2+of+the+AWS+Java+SDK+for+DynamoDB+%C2%B7+Rohan+Nagar%22+type%3Aissue+in%3Atitle+repo%3ARohanNagar%2Frohannagar.github.io

**Comment by jdanyow** [comment] 2019-02-08 03:15
Added a couple of issues to my testing repo with the same titles, then updated the `repo:` arg in the search queries... got the expected result:

1.https://github.com/issues?utf8=%E2%9C%93&q=%22Facebook+OAuth+using+SFAuthenticationSession+on+iOS+11+%C2%B7+Rohan+Nagar%22+is%3Aissue+in%3Atitle+repo%3Ajdanyow%2Futterances-demo
2. https://github.com/issues?utf8=%E2%9C%93&q=%22Migrating+to+Version+2+of+the+AWS+Java+SDK+for+DynamoDB+%C2%B7+Rohan+Nagar%22+is%3Aissue+in%3Atitle+repo%3Ajdanyow%2Futterances-demo

**Comment by jdanyow** [comment] 2019-02-08 03:18
Try editing this issue's title, then reverting the edit. Maybe this will force github to re-index.

https://github.com/RohanNagar/rohannagar.github.io/issues/2

**Comment by RohanNagar** [comment] 2019-02-08 03:31
Very strange.. I just tried as you suggested, doesn't seem to have changed..

**Comment by jdanyow** [comment] 2019-02-08 03:34
I think so- here's another thing you could try.

Create a new issue with title `Migrating to Version 2 of the AWS Java SDK for DynamoDB · Rohan Nagar`.

Then retry the issue search links in [my comment above](#issuecomment-461675145)

**Comment by RohanNagar** [comment] 2019-02-08 03:38
Just tried it, both of them now show up in the second search link. And utterances is still picking up the `Facebook OAuth using SFAuthenticationSession on iOS 11` for the latest post.

**Comment by jdanyow** [comment] 2019-02-08 03:42
That's so strange- added the two issue titles to [my repo](https://github.com/jdanyow/utterances-demo/issues) and it works as expected.

1.https://github.com/issues?utf8=%E2%9C%93&q=%22Facebook+OAuth+using+SFAuthenticationSession+on+iOS+11+%C2%B7+Rohan+Nagar%22+is%3Aissue+in%3Atitle+repo%3Ajdanyow%2Futterances-demo
2. https://github.com/issues?utf8=%E2%9C%93&q=%22Migrating+to+Version+2+of+the+AWS+Java+SDK+for+DynamoDB+%C2%B7+Rohan+Nagar%22+is%3Aissue+in%3Atitle+repo%3Ajdanyow%2Futterances-demo

**Comment by RohanNagar** [comment] 2019-02-08 03:49
I just sent an email to Github support so let's see what they say. Thanks for looking into it as well, this is a strange one.

**Comment by jdanyow** [comment] 2019-02-08 03:56
Sounds good- let me know what you find out.

**Comment by jdanyow** [comment] 2019-02-12 05:57
Hi @RohanNagar- just checking in. Any word from support on this?

**Comment by RohanNagar** [comment] 2019-02-12 17:59
I haven't heard anything yet. Just pinged them again, hopefully they can take a look soon..

**Comment by RohanNagar** [comment] 2019-02-14 23:56
Still haven't heard anything from support.. not sure what their usual response time is 🙁

**Comment by VonJane** [comment] 2019-03-21 07:45
Hello, I have the same problem. But  I'm using the url issue term.
this is my blog : 
 [https://www.janeblog.cn/#/Detail?articleId=530027293309927424](https://www.janeblog.cn/#/Detail?articleId=530027293309927424)
and the other one: [https://www.janeblog.cn/#/Detail?articleId=528626899967016960](https://www.janeblog.cn/#/Detail?articleId=528626899967016960) 
thank you for your help!

**Comment by RohanNagar** [comment] 2019-03-21 14:33
Well I wish I had an answer for you, but still no word from Github support. They say it's in their backlog.

**Comment by VonJane** [comment] 2019-03-22 01:00
OK，I'll do that.

**Comment by VonJane** [comment] 2019-03-29 06:36
@RohanNagar @jdanyow   I think it may be because my blog is a SPA project, and utterances does not seem to support SPA projects?

**Comment by jdanyow** [comment] 2019-04-07 14:20
@VonJane in your case, the blog post identifier is in the hash component of the URL (after the # symbol).

Utterances ignores the hash component because on most blogs this would cause duplicate github issues to be created. For example, consider these two links, each has a different hash but the url is to the same "blog post":
- https://github.com/utterance/utterances/blob/master/README.md#how-it-works
- https://github.com/utterance/utterances/blob/master/README.md#configuration

I think it would be good to use this configuration for your blog architecture:
```html
<script src="https://utteranc.es/client.js"
        repo="VonJane/Blog"
        issue-term="[ENTER ARTICLE ID HERE]"
        theme="github-light"
        crossorigin="anonymous"
        async>
</script>
```

For example, this post: https://www.janeblog.cn/#/Detail?articleId=530027293309927424
Would use the following utterances script:
```html
<script src="https://utteranc.es/client.js"
        repo="VonJane/Blog"
        issue-term="530027293309927424"
        theme="github-light"
        crossorigin="anonymous"
        async>
</script>
```

**Comment by VonJane** [comment] 2019-04-08 01:47
> @VonJane in your case, the blog post identifier is in the hash component of the URL (after the # symbol).
> 
> Utterances ignores the hash component because on most blogs this would cause duplicate github issues to be created. For example, consider these two links, each has a different hash but the url is to the same "blog post":
> 
> * https://github.com/utterance/utterances/blob/master/README.md#how-it-works
> * https://github.com/utterance/utterances/blob/master/README.md#configuration
> 
> I think it would be good to use this configuration for your blog architecture:
> 
> ```
> <script src="https://utteranc.es/client.js"
>         repo="VonJane/Blog"
>         issue-term="[ENTER ARTICLE ID HERE]" <---------------------------
>         theme="github-light"
>         crossorigin="anonymous"
>         async>
> </script>
> ```
> 
> For example, this post: https://www.janeblog.cn/#/Detail?articleId=530027293309927424
> Would use the following utterances script:
> 
> ```
> <script src="https://utteranc.es/client.js"
>         repo="VonJane/Blog"
>         issue-term="530027293309927424"
>         theme="github-light"
>         crossorigin="anonymous"
>         async>
> </script>
> ```

Thank you, I will try later.

**Comment by VonJane** [comment] 2019-04-08 03:13
@jdanyow Hello, I have solved this problem with the suggestions you provided, thank you again! Thank you!

**Comment by PhilipTrauner** [comment] 2019-05-30 23:21
Have you received a response from support yet @RohanNagar? I'm using the `og:title` issue term and I'm currently facing the same issue.

**Comment by RohanNagar** [comment] 2019-05-30 23:27
@PhilipTrauner I've pinged them multiple times with no ETA on when they will look at the issue. Would be great for you to chime in to support as well to hopefully get more visibility. Unfortunately I don't know how long it will take them to take a look, which is disappointing as it has been almost 4 months.

**Comment by PhilipTrauner** [comment] 2019-05-30 23:53
I think I just discovered what the actual issue is @RohanNagar.

If the issue title contains a number that is surrounded by two spaces, the `in:title` qualifier is ignored, and the `number` property of issues is also taken into consideration as a search term.

[\<space\>3\<space\>](https://github.com/PhilipTrauner/blog/issues?utf8=%E2%9C%93&q=%22+2+%22+type%3Aissue+in%3Atitle+)

[\<space\>3](https://github.com/PhilipTrauner/blog/issues?utf8=%E2%9C%93&q=%22+2%22+type%3Aissue+in%3Atitle+)

I'll also reach out the GitHub support with my findings 🙂

**Comment by RohanNagar** [comment] 2019-05-31 20:32
Nice find @PhilipTrauner! I see you opened a PR to workaround this. I suppose I could also change the title to not include a number surrounded by spaces. What a strange bug

**Comment by jdanyow** [comment] 2020-01-19 18:43
Closing, looks like this is fixed on github:

- https://github.com/issues?utf8=%E2%9C%93&q=%22Facebook+OAuth+using+SFAuthenticationSession+on+iOS+11+%C2%B7+Rohan+Nagar%22+is%3Aissue+in%3Atitle+repo%3A%22RohanNagar%2Frohannagar.github.io%22
- https://github.com/issues?utf8=%E2%9C%93&q=%22Migrating+to+Version+2+of+the+AWS+Java+SDK+for+DynamoDB+%C2%B7+Rohan+Nagar%22+type%3Aissue+in%3Atitle+repo%3ARohanNagar%2Frohannagar.github.io

**Closed by jdanyow** 2020-01-19 18:43 UTC
Labels: question
