### ISSUE TITLE
Mode with editing disabled / link to the Issue page?

### ISSUE THREAD

**Issue by mmt** [utterance/utterances#456] opened 2021-01-02 07:08 UTC
Hi there,

Thanks for making such a useful App.  I'm not comfortable asking anyone visiting my blog to hand over "Act on your behalf" privileges to a third party app, and I'm wondering if there could be a mode where:
- All comments are displayed on the site.
- There is a button that will take you to the appropriate issue page to comment on if you want to add a comment (and create it if it doesn't exist).

I do want to be clear that I don't think there will be any malicious intent on the part of the utterances authors, I'm just concerned that the more users authorize this one app to "Act on their Behalf", the more tempting a target the project will be to attack.

Thanks for hearing me out, and again thanks for the great software.

**Comment by TysonMN** [comment] 2021-01-02 12:45
I think this is a duplicate of #355.

**Comment by BrevitasEU** [comment] 2021-01-04 17:20
also see #374

**Closed** 2021-02-06 19:55 UTC
Labels: duplicate
